export const employers = [
  'Wal-Mart Stores',
  'Exxon Mobil',
  'Chevron',
  'Berkshire Hathaway',
  'Apple',
  'Phillips 66',
  'General Motors',
  'Ford Motor',
  'General Electric',
  'Valero Energy',
  'AT&T',
  'CVS Caremark',
  'Fannie Mae',
  'UnitedHealth Group',
  'McKesson',
  'Verizon Communications',
  'Hewlett-Packard',
  'J.P. Morgan Chase & Co.',
  'Costco Wholesale',
  'Express Scripts Holding'
]
